---
- hosts: all
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: Gather all facts
    setup:
        gather_subset:
          - 'all'
    register: res
  - name: Display gathered facts
    debug: var=res

  - name: Disabling SELINUX 
    selinux:
     state: disabled

  - name: Run Setenforce command
    command: sudo setenforce 0

  - name: Install packages that allow yum to be used over HTTPS
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - varnish 
      - ca-certificates
      - curl
      - gnupg
      - device-mapper-persistent-data
      - lvm2
      - yum-utils

  - name: Add yum repository for stable version
    yum_repository:
      name: Dockerce
      description: Docker CE Repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7 
      gpgkey: https://yum.dockerproject.org/gpg 
      state: present 

  - name: Install docker and its dependecies
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
 
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a

  - name: Add yum repository for stable version
    yum_repository:
      name: kubernetes 
      description: Kubernetes Repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg 
      state: present 

  - name: Install Kubernetes binaries
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

